### PR TITLE
Support ES modules

### PR DESCRIPTION
**Pull request by matewilk**
This PR allows for treating  the `use-dabounce` library as a [ES module](https://nodejs.org/dist/latest-v13.x/docs/api/esm.html#esm_ecmascript_modules)

Adds 
`type: "module"` to `package.json` file
Changes
`jest.config.js` file extension to `jest.config.cjs` - to opt out of ESM for this file

### CODE REVIEW

**Comment by matewilk** [comment]
Apologies for force pushes, didn't know how to properly link an issue with a PR. Now I know 😄

**Comment by matewilk** [comment]
I'm seeing the build is failing, I think it might be due to the fact that the build uses node v12. I think the ES modules are supported from node v16.

**Comment by xnimorz** [comment]
Resolved failures in https://github.com/xnimorz/use-debounce/pull/150

**Comment by xnimorz** [comment]
Thanks for the contribution @matewilk I'll cut a new release soon

**Comment by xnimorz** [comment]
Github action report: https://github.com/xnimorz/use-debounce/actions/runs/3569486941/jobs/5999497098

**Comment by matewilk** [comment]
Thank you @xnimorz, appreciate your library and prompt responses and actions

**Pull request merged**
